require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SitePagesController do

  def mock_site_page(stubs={})
    @mock_site_page ||= mock_model(SitePage, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all site_pages as @site_pages" do
      SitePage.stub(:all) { [mock_site_page] }
      get :index
      assigns(:site_pages).should eq([mock_site_page])
    end
  end

  describe "GET show" do
    it "assigns the requested site_page as @site_page" do
      SitePage.stub(:find).with("37") { mock_site_page }
      get :show, :id => "37"
      assigns(:site_page).should be(mock_site_page)
    end
  end

  describe "GET new" do
    it "assigns a new site_page as @site_page" do
      SitePage.stub(:new) { mock_site_page }
      get :new
      assigns(:site_page).should be(mock_site_page)
    end
  end

  describe "GET edit" do
    it "assigns the requested site_page as @site_page" do
      SitePage.stub(:find).with("37") { mock_site_page }
      get :edit, :id => "37"
      assigns(:site_page).should be(mock_site_page)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created site_page as @site_page" do
        SitePage.stub(:new).with({'these' => 'params'}) { mock_site_page(:save => true) }
        post :create, :site_page => {'these' => 'params'}
        assigns(:site_page).should be(mock_site_page)
      end

      it "redirects to the created site_page" do
        SitePage.stub(:new) { mock_site_page(:save => true) }
        post :create, :site_page => {}
        response.should redirect_to(site_page_url(mock_site_page))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved site_page as @site_page" do
        SitePage.stub(:new).with({'these' => 'params'}) { mock_site_page(:save => false) }
        post :create, :site_page => {'these' => 'params'}
        assigns(:site_page).should be(mock_site_page)
      end

      it "re-renders the 'new' template" do
        SitePage.stub(:new) { mock_site_page(:save => false) }
        post :create, :site_page => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested site_page" do
        SitePage.stub(:find).with("37") { mock_site_page }
        mock_site_page.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :site_page => {'these' => 'params'}
      end

      it "assigns the requested site_page as @site_page" do
        SitePage.stub(:find) { mock_site_page(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:site_page).should be(mock_site_page)
      end

      it "redirects to the site_page" do
        SitePage.stub(:find) { mock_site_page(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(site_page_url(mock_site_page))
      end
    end

    describe "with invalid params" do
      it "assigns the site_page as @site_page" do
        SitePage.stub(:find) { mock_site_page(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:site_page).should be(mock_site_page)
      end

      it "re-renders the 'edit' template" do
        SitePage.stub(:find) { mock_site_page(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested site_page" do
      SitePage.stub(:find).with("37") { mock_site_page }
      mock_site_page.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the site_pages list" do
      SitePage.stub(:find) { mock_site_page }
      delete :destroy, :id => "1"
      response.should redirect_to(site_pages_url)
    end
  end

end
